Mark tests
ModECI/MDF pull request #305
Opened 2022-08-02 19:20 UTC by parikshit14

@davidt0x updated the branch as discussed. 
- Though I didn't change `setup.py` for `[test]` because I think it should remain in the dev installation as to test locally one doesn't need to install the entire list of optional packages.
- As discussed with @pgleeson, we wanted to have `PyTorch` as core dependencies as we provide specifically high functionalities and examples for it, so we might want to think about that.

2022-08-02 19:52 UTC, davidt0x requested changes
I think pytorch shouldn't be a core requirement if we can avoid it but I will discuss with @pgleeson tomorrow in our meeting.

2022-08-02 19:52 UTC, davidt0x commented on setup.cfg
>      h5py
Remove this copy of h5py

2022-08-02 19:52 UTC, davidt0x commented on setup.py
> +        "pyNeuroML>=0.5.20",
I think these should be broken apart into individual extra requirements for each backend, Something like:
```
extras = {
    "psyneulink": ["psyneulink>=0.12.0.0"],
    "neuroml": ["pyNeuroML>=0.5.20", "neuromllite>=0.5.1"],
 ...

```       

We can then have `optional` be all core plus all backed requirements.

2022-08-03 17:44 UTC, davidt0x commented
Note sure what is causing the CI fails on linux and windows. Might be tricky to debug, looks like an out of memory error maybe.

2022-08-03 17:51 UTC, parikshit14 commented
> Note sure what is causing the CI fails on linux and windows. Might be tricky to debug, looks like an out of memory error maybe.

yes, I ran the "not core" tests locally and it was crashing there as well after few minutes.

2022-08-03 19:11 UTC, davidt0x commented
I think this is being because modelspec 0.2.4 is being installed in place of the github repo version when optional dependencies are installed. There was a bug fix after 0.2.4 (not sure if its in 0.2.5 or later). The bug was that the evaluate function was causing all the tensors to be formatted to strings regardless of whether they were actually printing or not. Anyway, the root cause is that somewhere pip thinks it needs 0.2.4 when in should be pinned higher.

2022-08-04 15:59 UTC, pgleeson commented
@parikshit14 Try pulling in the latest changes from the development branch to yours, some of the issues with getting the correct version of modelspec/psyneulink are resolved there.

2022-08-05 15:04 UTC, pgleeson commented
@parikshit14 This PR contains a lot of extra files related to the updates for integrating the readmes into the docs. These have already been selectively integrated into the docs (many image/py/json files are not yet required), so could you open a fresh PR with just the changes for marking the tests (ci.yml, setup.py etc)?

2022-08-09 12:13 UTC, closed without merging